// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import { Test } from "forge-std/Test.sol";
import { stdJson } from "forge-std/StdJson.sol";
import { Base64 } from "solady/src/utils/Base64.sol";
import { FatPunks } from "../src/FatPunks.sol";
import { FatPunksRenderer } from "../src/FatPunksRenderer.sol";
import { MockCryptopunksData } from "../src/MockCryptopunksData.sol";
import { ICryptopunksData } from "../src/interfaces/ICryptopunksData.sol";
import { IFatRenderer } from "../src/interfaces/IFatRenderer.sol";

contract RendererTest is Test {
    using stdJson for string;

    FatPunksRenderer renderer;
    MockCryptopunksData mock;
    uint16[9] FIXTURES = [0, 1, 2, 3, 4, 5, 117, 372, 635]; // incl zombie/ape/alien

    function setUp() public {
        mock = new MockCryptopunksData();
        string memory json =
            vm.readFile("test/fixtures/punks.json");
        for (uint256 i = 0; i < FIXTURES.length; i++) {
            bytes memory rgba = json.readBytes(
                string(abi.encodePacked(".", vm.toString(uint256(FIXTURES[i])))));
            mock.setPunk(FIXTURES[i], rgba);
        }
        bytes memory punk0 = json.readBytes(".0");
        mock.setPunk(7900, punk0);
        mock.setPunk(9999, punk0);
        mock.setPunkAttributes(0, "Female 2, Earring, Blonde Bob, Green Eye Shadow");
        mock.setPunkAttributes(7900, "Female 3, Hot Lipstick, Straight Hair Dark, Clown Eyes Blue");
        mock.setPunkAttributes(9999, "Female 1, Mohawk, Nerd Glasses");
        mock.setPunkAttributes(117, "Zombie, Front Beard Dark, Messy Hair");
        mock.setPunkAttributes(372, "Ape, Cap Forward");
        mock.setPunkAttributes(635, "Alien, Bandana, Regular Shades");
        renderer = new FatPunksRenderer(ICryptopunksData(address(mock)));
    }

    function test_eip170() public view {
        assertLe(address(renderer).code.length, 24_576, "renderer exceeds EIP-170");
    }

    function test_bodyLevelsShapeAndDeterminism() public view {
        bytes memory a = renderer.bodyLevels(0, 20);
        bytes memory b = renderer.bodyLevels(0, 20);
        assertEq(a.length, 1024);
        assertEq(keccak256(a), keccak256(b));
        // values in 0..4
        for (uint256 i = 0; i < 1024; i++) {
            assertLe(uint8(a[i]), 4);
        }
    }

    function test_levelChangesOutput() public view {
        bytes memory slim = renderer.bodyLevels(0, 0);
        bytes memory fat = renderer.bodyLevels(0, 20);
        assertTrue(keccak256(slim) != keccak256(fat),
            "conditioning has no effect");
    }

    function test_svgStructure() public view {
        string memory s = renderer.svg(0, 20);
        bytes memory b = bytes(s);
        assertGt(b.length, 200);
        // starts with <svg, ends with </svg>
        assertEq(b[0], "<");
        assertEq(b[1], "s");
        assertEq(b[b.length - 1], ">");
    }

    function test_tokenURIStructure() public view {
        string memory uri = renderer.tokenURI(0, 7);
        bytes memory b = bytes(uri);
        bytes memory prefix = "data:application/json;base64,";
        for (uint256 i = 0; i < prefix.length; i++) {
            assertEq(b[i], prefix[i]);
        }
        string memory metadata = _decodeDataUri(uri, string(prefix));
        assertEq(metadata.readString(".name"), "Fat Punk #0");
        assertGt(bytes(metadata.readString(".image")).length, 100);
    }

    function test_tokenURIHasOpenSeaAttributes7900() public view {
        string memory metadata = _decodeTokenURI(7900, 1);

        assertEq(metadata.readString(".name"), "Fat Punk #7900");
        assertEq(
            metadata.readString(".description"),
            "Fat Punk #7900. Feed it burritos until it becomes an absolute unit. Fully on-chain fatness, generated by a tiny neural network living inside the contract."
        );
        assertAccessory(metadata, 0, "Hot Lipstick");
        assertAccessory(metadata, 1, "Clown Eyes Blue");
        assertAccessory(metadata, 2, "Straight Hair Dark");
        assertAccessory(metadata, 3, "3 attributes");
        assertEq(metadata.readString(".attributes[4].trait_type"), "Type");
        assertEq(metadata.readString(".attributes[4].value"), "Female");
        assertEq(metadata.readString(".attributes[5].trait_type"), "Fatness Level");
        assertEq(metadata.readUint(".attributes[5].value"), 1);
        assertEq(metadata.readString(".attributes[6].trait_type"), "Fatness Category");
        assertEq(metadata.readString(".attributes[6].value"), "Slim");
        assertFalse(_contains(metadata, "Original Punk ID"));
        assertFalse(_contains(metadata, "Original Punk Type"));
        assertFalse(_contains(metadata, "Original Attribute Count"));
        assertFalse(_contains(metadata, '"value":"Female 3"'));

        string memory image = metadata.readString(".image");
        string memory svg = _decodeDataUri(image, "data:image/svg+xml;base64,");
        bytes memory svgBytes = bytes(svg);
        assertEq(svgBytes[0], "<");
        assertEq(svgBytes[1], "s");
    }

    function test_originalPunkIdMappingNoOffByOne() public view {
        string memory metadata0 = _decodeTokenURI(0, 0);
        assertEq(metadata0.readString(".name"), "Fat Punk #0");
        assertAccessory(metadata0, 0, "Earring");
        assertAccessory(metadata0, 1, "Green Eye Shadow");
        assertAccessory(metadata0, 2, "Blonde Bob");
        assertAccessory(metadata0, 3, "3 attributes");
        assertEq(metadata0.readString(".attributes[4].trait_type"), "Type");
        assertEq(metadata0.readString(".attributes[4].value"), "Female");

        string memory metadata7900 = _decodeTokenURI(7900, 1);
        assertEq(metadata7900.readString(".name"), "Fat Punk #7900");
        assertEq(metadata7900.readString(".attributes[4].value"), "Female");

        string memory metadata9999 = _decodeTokenURI(9999, 20);
        assertEq(metadata9999.readString(".name"), "Fat Punk #9999");
        assertAccessory(metadata9999, 0, "Nerd Glasses");
        assertAccessory(metadata9999, 1, "Mohawk");
        assertAccessory(metadata9999, 2, "2 attributes");
        assertEq(metadata9999.readString(".attributes[3].trait_type"), "Type");
        assertEq(metadata9999.readString(".attributes[3].value"), "Female");
    }

    function test_specialPunkTypesAndAccessoryCounts() public view {
        string memory zombie = _decodeTokenURI(117, 4);
        assertAccessory(zombie, 0, "Front Beard Dark");
        assertAccessory(zombie, 1, "Messy Hair");
        assertAccessory(zombie, 2, "2 attributes");
        assertEq(zombie.readString(".attributes[3].trait_type"), "Type");
        assertEq(zombie.readString(".attributes[3].value"), "Zombie");

        string memory ape = _decodeTokenURI(372, 8);
        assertAccessory(ape, 0, "Cap Forward");
        assertAccessory(ape, 1, "1 attributes");
        assertEq(ape.readString(".attributes[2].trait_type"), "Type");
        assertEq(ape.readString(".attributes[2].value"), "Ape");

        string memory alien = _decodeTokenURI(635, 20);
        assertAccessory(alien, 0, "Regular Shades");
        assertAccessory(alien, 1, "Bandana");
        assertAccessory(alien, 2, "2 attributes");
        assertEq(alien.readString(".attributes[3].trait_type"), "Type");
        assertEq(alien.readString(".attributes[3].value"), "Alien");
    }

    function test_fatPunksTokenCompatibility() public {
        address[] memory allowed = new address[](1);
        allowed[0] = address(0x5EA);
        FatPunks nft = new FatPunks(allowed, IFatRenderer(address(renderer)));
        nft.setMaxSupply(10_000);
        address owner = address(0xA11CE);

        vm.prank(allowed[0]);
        nft.mintSeaDrop(owner, 1);

        string memory metadata0 = _decodeTokenURIString(nft.tokenURI(7900));
        assertEq(metadata0.readString(".name"), "Fat Punk #7900");
        assertEq(metadata0.readString(".attributes[4].value"), "Female");
        assertEq(metadata0.readUint(".attributes[5].value"), 0);

        vm.prank(owner);
        nft.feed(7900);
        string memory metadata1 = _decodeTokenURIString(nft.tokenURI(7900));
        assertEq(metadata1.readString(".name"), "Fat Punk #7900");
        assertEq(metadata1.readString(".attributes[4].value"), "Female");
        assertEq(metadata1.readUint(".attributes[5].value"), 1);
        assertGt(bytes(nft.previewSvg(7900, 1)).length, 200);
    }

    function test_allFixturesRender() public view {
        for (uint256 i = 0; i < FIXTURES.length; i++) {
            string memory s = renderer.svg(FIXTURES[i], uint8((i * 5) % 21));
            assertGt(bytes(s).length, 200);
        }
    }

    function test_gasRender() public {
        uint256 g0 = gasleft();
        renderer.bodyLevels(0, 20);
        uint256 gBody = g0 - gasleft();
        g0 = gasleft();
        renderer.tokenURI(0, 20);
        uint256 gUri = g0 - gasleft();
        // view-call budget sanity (eth_call default caps are far higher)
        emit log_named_uint("gas bodyLevels", gBody);
        emit log_named_uint("gas tokenURI", gUri);
        assertLt(gUri, 1_000_000_000);
    }

    function assertAccessory(
        string memory metadata,
        uint256 index,
        string memory expectedValue
    ) internal pure {
        assertEq(metadata.readString(
            string(abi.encodePacked(".attributes[", vm.toString(index), "].trait_type"))
        ), "Accessory");
        assertEq(metadata.readString(
            string(abi.encodePacked(".attributes[", vm.toString(index), "].value"))
        ), expectedValue);
    }

    function _decodeTokenURI(uint256 tokenId, uint8 level)
        internal view returns (string memory)
    {
        return _decodeTokenURIString(renderer.tokenURI(tokenId, level));
    }

    function _decodeTokenURIString(string memory uri)
        internal pure returns (string memory)
    {
        return _decodeDataUri(uri, "data:application/json;base64,");
    }

    function _decodeDataUri(string memory uri, string memory prefix)
        internal pure returns (string memory)
    {
        bytes memory uriBytes = bytes(uri);
        bytes memory prefixBytes = bytes(prefix);
        for (uint256 i = 0; i < prefixBytes.length; ++i) {
            assertEq(uriBytes[i], prefixBytes[i]);
        }
        bytes memory encoded = new bytes(uriBytes.length - prefixBytes.length);
        for (uint256 i = prefixBytes.length; i < uriBytes.length; ++i) {
            encoded[i - prefixBytes.length] = uriBytes[i];
        }
        return string(Base64.decode(string(encoded)));
    }

    function _contains(string memory haystack, string memory needle)
        internal pure returns (bool)
    {
        bytes memory h = bytes(haystack);
        bytes memory n = bytes(needle);
        if (n.length == 0 || n.length > h.length) return false;
        for (uint256 i = 0; i <= h.length - n.length; ++i) {
            bool found = true;
            for (uint256 j = 0; j < n.length; ++j) {
                if (h[i + j] != n[j]) {
                    found = false;
                    break;
                }
            }
            if (found) return true;
        }
        return false;
    }
}

/// @notice Mainnet-fork render against the REAL CryptopunksData.
///         Run: MAINNET_RPC_URL=... forge test --match-contract ForkRender -vv
contract ForkRenderTest is Test {
    address constant PUNKS_DATA = 0x16F5A35647D6F03D5D3da7b35409D65ba03aF3B2;
    address constant CURRENT_RENDERER = 0x82913CC30E3289f344a5ac32829Fe4B24F68ff1f;

    function test_forkRender() public {
        string memory rpc = vm.envOr("MAINNET_RPC_URL", string(""));
        if (bytes(rpc).length == 0) {
            emit log("skipped: set MAINNET_RPC_URL to run the fork test");
            return;
        }
        vm.createSelectFork(rpc);
        FatPunksRenderer r =
            new FatPunksRenderer(ICryptopunksData(PUNKS_DATA));
        // zombie 117, ape 372, alien 635 against the canonical store
        string memory s = r.svg(635, 20);
        assertGt(bytes(s).length, 200);
        emit log_named_uint("alien svg bytes", bytes(s).length);
    }

    function test_forkMetadataAndArtParity7900() public {
        string memory rpc = vm.envOr("MAINNET_RPC_URL", string(""));
        if (bytes(rpc).length == 0) {
            emit log("skipped: set MAINNET_RPC_URL to run the fork test");
            return;
        }
        vm.createSelectFork(rpc);
        FatPunksRenderer r =
            new FatPunksRenderer(ICryptopunksData(PUNKS_DATA));

        string memory raw =
            ICryptopunksData(PUNKS_DATA).punkAttributes(7900);
        assertEq(raw, "Female 3, Hot Lipstick, Straight Hair Dark, Clown Eyes Blue");

        string memory oldSvg = IFatRenderer(CURRENT_RENDERER).svg(7900, 1);
        string memory newSvg = r.svg(7900, 1);
        assertEq(keccak256(bytes(newSvg)), keccak256(bytes(oldSvg)));
        assertEq(
            keccak256(bytes(newSvg)),
            0x041a3f18e5e33538f41b50f7ea7d08a9394f1b1330ea69ce2e72363702464dbf
        );

        string memory uri = r.tokenURI(7900, 1);
        bytes memory prefix = "data:application/json;base64,";
        bytes memory uriBytes = bytes(uri);
        for (uint256 i = 0; i < prefix.length; ++i) {
            assertEq(uriBytes[i], prefix[i]);
        }
        emit log_named_string("canonical 7900", raw);
        emit log_named_bytes32("7900 svg hash", keccak256(bytes(newSvg)));
        emit log_named_uint("7900 metadata bytes", uriBytes.length);
    }
}
